apiVersion: v1
kind: Secret
metadata:
  name: app-points-db-secret
  namespace: taskmaster
type: Opaque
stringData:
  DATABASE_URL: postgresql+psycopg2://app_user:app_pass@app-postgres:5432/app_db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-points
  namespace: taskmaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-points
  template:
    metadata:
      labels:
        app: app-points
    spec:
      containers:
      - name: app-points
        image: registry.deti/taskmaster/app-points:v1
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-points-db-secret
              key: DATABASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: app-points-service
  namespace: taskmaster
spec:
  selector:
    app: app-points
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-postgres
  namespace: taskmaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-postgres
  template:
    metadata:
      labels:
        app: app-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: app_db
        - name: POSTGRES_USER
          value: app_user
        - name: POSTGRES_PASSWORD
          value: app_pass
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
      volumes:
      - name: postgres-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: app-postgres
  namespace: taskmaster
spec:
  selector:
    app: app-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
