<#
.SYNOPSIS
  Windows port of setup_mosquitto_tls.sh for ESP-Arcade.

  Generates a local CA + a Mosquitto server certificate bound to this PC's IP,
  writes a Mosquitto TLS config + password file, copies the CA into the firmware,
  and updates main/generated_mqtt_config.h and arcade-dashboard/mqtt-config.json.

.PARAMETER Ip
  IP the ESP32 will use to reach the broker. Defaults to the Wi-Fi IPv4.
  Re-run with -Ip <addr> when you join the phone hotspot, then rebuild the firmware.

.EXAMPLE
  .\scripts\setup_mosquitto_tls.ps1
  .\scripts\setup_mosquitto_tls.ps1 -Ip 192.168.43.50
#>
param(
    [string]$Ip = "",
    [string]$MosqDir  = "C:\Program Files\mosquitto",
    [string]$Username = "arcade",
    [string]$Password = "arcade-local-2026",
    [int]$DaysCA      = 3650,
    [int]$DaysServer  = 825
)

$ErrorActionPreference = 'Stop'
# Stop Git's MSYS layer from rewriting paths/args passed to openssl.
$env:MSYS_NO_PATHCONV   = '1'
$env:MSYS2_ARG_CONV_EXCL = '*'

# openssl is usually NOT on PowerShell's PATH (only inside Git Bash). Resolve it
# explicitly, falling back to the copy bundled with Git for Windows.
$OpenSsl = (Get-Command openssl -ErrorAction SilentlyContinue).Source
if (-not $OpenSsl) {
    foreach ($cand in @(
        "$env:ProgramFiles\Git\usr\bin\openssl.exe",
        "$env:ProgramFiles\Git\mingw64\bin\openssl.exe",
        "${env:ProgramFiles(x86)}\Git\usr\bin\openssl.exe")) {
        if (Test-Path $cand) { $OpenSsl = $cand; break }
    }
}
if (-not $OpenSsl) {
    throw "openssl not found. Install Git for Windows, or run scripts\run.sh from Git Bash instead."
}

$Root    = Split-Path -Parent $PSScriptRoot
$CertDir = Join-Path $Root ".local\mqtt-certs"
New-Item -ItemType Directory -Force $CertDir | Out-Null

# ---- collect candidate IPv4s (skip loopback / link-local / VirtualBox) ----
$cands = Get-NetIPAddress -AddressFamily IPv4 |
    Where-Object { $_.IPAddress -notlike '127.*' -and $_.IPAddress -notlike '169.254.*' -and $_.IPAddress -ne '192.168.56.1' }

if (-not $Ip) {
    $wifi = $cands | Where-Object { $_.InterfaceAlias -like 'Wi-Fi*' } | Select-Object -First 1
    if ($wifi) { $Ip = $wifi.IPAddress }
    elseif ($cands) { $Ip = ($cands | Select-Object -First 1).IPAddress }
    else { throw "No usable IPv4 address found. Pass -Ip <addr> explicitly." }
}
Write-Host "Using broker IP: $Ip" -ForegroundColor Cyan

# openssl from Git for Windows is on PATH; use forward-slash paths for MSYS.
function U([string]$p) { return ($p -replace '\\', '/') }

$caKey = "$CertDir\arcade-ca.key";    $caCrt = "$CertDir\arcade-ca.crt"
$srvKey = "$CertDir\arcade-server.key"; $srvCsr = "$CertDir\arcade-server.csr"
$srvCrt = "$CertDir\arcade-server.crt"; $srvCnf = "$CertDir\arcade-server.cnf"
$passwd = "$CertDir\arcade.passwd"
$conf   = "$CertDir\mosquitto-arcade.conf"

# PowerShell 5.1 promotes any native-tool stderr to a terminating error when
# ErrorActionPreference is 'Stop'. openssl prints its key-gen progress to stderr,
# so relax the preference around the native calls; correctness is still gated on
# $LASTEXITCODE below.
$ErrorActionPreference = 'Continue'

# ---- 1. local CA (reused if it already exists) ----
if (-not (Test-Path $caCrt)) {
    Write-Host "Generating local CA..."
    & $OpenSsl req -x509 -newkey rsa:2048 -nodes -keyout (U $caKey) -out (U $caCrt) `
        -days $DaysCA -subj "/CN=ESP-Arcade Local CA" 2>$null
    if ($LASTEXITCODE) { throw "openssl CA generation failed" }
} else {
    Write-Host "Reusing existing CA: $caCrt"
}

# ---- 2. server certificate with SAN = chosen IP + all local IPs + localhost ----
$ipList = @($Ip, '127.0.0.1') + ($cands | ForEach-Object { $_.IPAddress }) | Select-Object -Unique
$san = ""
$n = 1
foreach ($ipa in $ipList) { $san += "IP.$n = $ipa`r`n"; $n++ }

$cnf = @"
[req]
distinguished_name = dn
req_extensions = v3_req
prompt = no
[dn]
CN = $Ip
[v3_req]
subjectAltName = @alt_names
[alt_names]
DNS.1 = localhost
$san
"@
Set-Content -Path $srvCnf -Value $cnf -Encoding ascii

Write-Host "Generating server certificate (SAN bound to $Ip)..."
& $OpenSsl req -new -newkey rsa:2048 -nodes -keyout (U $srvKey) -out (U $srvCsr) -config (U $srvCnf) 2>$null
if ($LASTEXITCODE) { throw "openssl CSR generation failed" }
& $OpenSsl x509 -req -in (U $srvCsr) -CA (U $caCrt) -CAkey (U $caKey) -CAcreateserial `
    -out (U $srvCrt) -days $DaysServer -extensions v3_req -extfile (U $srvCnf) 2>$null
if ($LASTEXITCODE) { throw "openssl server cert signing failed" }

# ---- 3. password file ----
Write-Host "Writing password file for user '$Username'..."
& "$MosqDir\mosquitto_passwd.exe" -c -b $passwd $Username $Password
if ($LASTEXITCODE) { throw "mosquitto_passwd failed" }
$ErrorActionPreference = 'Stop'   # restore strict handling for the file writes below

# ---- 4. Mosquitto TLS listener config ----
$confText = @"
# ESP-Arcade local TLS broker (generated by setup_mosquitto_tls.ps1)
per_listener_settings true

listener 8883
cafile $caCrt
certfile $srvCrt
keyfile $srvKey
require_certificate false
allow_anonymous false
password_file $passwd
"@
Set-Content -Path $conf -Value $confText -Encoding ascii

# ---- 5. wire the CA + config into the firmware and dashboard ----
Copy-Item $caCrt "$Root\main\mqtt_broker_ca.pem" -Force

$header = @"
#ifndef GENERATED_MQTT_CONFIG_H
#define GENERATED_MQTT_CONFIG_H

/*
 * Generated by scripts/setup_mosquitto_tls.ps1.
 * Re-run that script (and rebuild the firmware) whenever this PC's IP changes.
 */
#define ARCADE_MQTT_BROKER_IP   "$Ip"
#define ARCADE_MQTT_BROKER_PORT 8883
#define ARCADE_MQTT_BROKER_URI  "mqtts://${Ip}:8883"
#define ARCADE_MQTT_USERNAME    "$Username"
#define ARCADE_MQTT_PASSWORD    "$Password"

#endif
"@
Set-Content -Path "$Root\main\generated_mqtt_config.h" -Value $header -Encoding ascii

$json = @"
{
  "brokerUrl": "mqtts://127.0.0.1:8883",
  "caFile": "../main/mqtt_broker_ca.pem",
  "username": "$Username",
  "password": "$Password"
}
"@
Set-Content -Path "$Root\arcade-dashboard\mqtt-config.json" -Value $json -Encoding ascii

Write-Host ""
Write-Host "Done." -ForegroundColor Green
Write-Host "Broker IP:        $Ip"
Write-Host "TLS URI:          mqtts://${Ip}:8883"
Write-Host "CA (firmware):    $Root\main\mqtt_broker_ca.pem"
Write-Host "Config header:    $Root\main\generated_mqtt_config.h"
Write-Host "Dashboard config: $Root\arcade-dashboard\mqtt-config.json"
Write-Host ""
Write-Host "Start the broker (keep this window open):" -ForegroundColor Yellow
Write-Host "  & '$MosqDir\mosquitto.exe' -c '$conf' -v"
Write-Host ""
Write-Host "Quick self-test from another terminal:"
Write-Host "  & '$MosqDir\mosquitto_sub.exe' -h $Ip -p 8883 --cafile '$caCrt' -u $Username -P '$Password' -t arcade/status -v"
