apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfc-server-deployment
  namespace: taskmaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfc-server
  template:
    metadata:
      labels:
        app: nfc-server
    spec:
      containers:
      - name: nfc-server
        image: registry.deti/taskmaster/nfc-server:v1
        ports:
        - containerPort: 5000
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka-service:9092
---
apiVersion: v1
kind: Service
metadata:
  name: nfc-service
  namespace: taskmaster
spec:
  selector:
    app: nfc-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP