FROM python:3.10

RUN apt-get update && apt-get install -y --no-install-recommends

WORKDIR /app

COPY requirements.txt /app/
RUN pip install -r requirements.txt

COPY testNFC.py /app/
COPY database /app/database

ENV PORT=5000
CMD ["python", "testNFC.py"]