#ifndef GENERATED_MQTT_CONFIG_H
#define GENERATED_MQTT_CONFIG_H

/* Generated by run.sh. Re-run it (and rebuild+flash the firmware) when the PC IP changes. */
#define ARCADE_MQTT_BROKER_IP   "10.118.117.215"
#define ARCADE_MQTT_BROKER_PORT 8883
#define ARCADE_MQTT_BROKER_URI  "mqtts://10.118.117.215:8883"
#define ARCADE_MQTT_USERNAME    "arcade"
#define ARCADE_MQTT_PASSWORD    "arcade-local-2026"

#endif
