FROM python:3.10

RUN apt-get update && apt-get install -y --no-install-recommends

WORKDIR /app

COPY requirements.txt /app/
RUN pip install -r requirements.txt

COPY consumer_nfc.py /app/
COPY database /app/database

ENV PORT=5001
CMD ["python", "consumer_nfc.py"]