apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: taskMaster
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: registry.deti/taskMaster/auth:v1
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: auth-config
            - secretRef:
                name: auth-secret
