apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-nfc
  namespace: taskMaster
  labels:
    app: consumer-nfc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-nfc
  template:
    metadata:
      labels:
        app: consumer-nfc
    spec:
      containers:
        - name: consumer
          image: registry.deti/taskMaster/consumer-nfc:v1
          command: ["python"]
          args: ["consumer_nfc.py"]
          envFrom:
            - configMapRef:
                name: auth-config
