FROM python:3.10

RUN apt-get update && apt-get install -y --no-install-recommends

WORKDIR /app

COPY requirements.txt /app/
RUN pip install -r requirements.txt

COPY auth.py /app/
COPY nfc_system_final/nfc_backend/database /app/database

ENV FLASK_APP=auth.py
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
