apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfc-deployment
  namespace: taskmaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfc
  template:
    metadata:
      labels:
        app: nfc
    spec:
      containers:
      - name: nfc
        image: registry.deti/taskmaster/nfc:v3
        ports:
        - containerPort: 5001
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka-service:9092
---
apiVersion: v1
kind: Service
metadata:
  name: nfc-service
  namespace: taskmaster
spec:
  selector:
    app: nfc
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001
  type: ClusterIP
