apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-notifications
  namespace: prof
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-notifications
  template:
    metadata:
      labels:
        app: app-notifications
    spec:
      containers:
      - name: app-notifications
        image: registry.deti:5000/prof/app-notifications:v1
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: app-notifications-service
  namespace: prof
spec:
  selector:
    app: app-notifications
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
